[project]
name = "EasyTicket"
version = "0.0.1"
authors = [
  { name="F18-Maverick", email="xu_ruihong2009@163.com" },
]
description = "Get ticket on 12306 by web crawler and selenium driveing the system browser"
dependencies=["selenium>4.0.0"]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/F18-Maverick/EasyTicket"
Issues = "https://github.com/F18-Maverick/EasyTicket/issues"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
